const SKEY='aisp-formal-session-v1',RKEY='aisp-formal-records-v1';
const state={cases:[],caseId:'aphasia_001',caseData:null,mode:'training',studentName:'',transcript:[],revealedFactIds:[],sessionId:null,records:[],coach:null};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=> 'session_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const modeLabel=m=>m==='exam'?'考試評量':'訓練學習';

function save(){write(SKEY,{caseId:state.caseId,mode:state.mode,studentName:state.studentName,transcript:state.transcript,revealedFactIds:state.revealedFactIds,sessionId:state.sessionId,coach:state.coach});}
function start(){state.sessionId=uid();state.transcript=[{role:'patient',content:state.caseData.opening,at:new Date().toISOString()}];state.revealedFactIds=[];state.coach=null;$('resultCard').classList.add('hidden');save();renderAll();}
function renderAll(){renderHeader();renderMode();renderChat();renderCoach();}
function renderHeader(){$('caseSelect').value=state.caseId;$('modeSelect').value=state.mode;$('studentName').value=state.studentName;$('caseTitle').textContent=state.caseData.title;$('caseBrief').textContent=state.caseData.publicBrief||'';$('difficultyBadge').textContent=state.caseData.difficulty||'自訂';$('patientSummary').textContent=(state.caseData.patient?.name||'模擬病人')+'，'+(state.caseData.patient?.age||'--')+' 歲';}
function renderMode(){const training=state.mode==='training';$('modeBanner').className='mode-banner '+(training?'training':'exam');$('modeBadge').textContent=training?'TRAINING':'EXAM';$('modeTitle').textContent=training?'訓練學習模式':'考試評量模式';$('modeDescription').textContent=training?'AI 教練會在每輪後提供問句品質與下一步方向，但不直接揭露病例答案。':'不提供即時提示、不顯示評量進度；結束後才產生完整評量與總評。';$('coachCard').classList.toggle('hidden',!training);$('trainingProgressMetric').classList.toggle('hidden',!training);$('examProgressHidden').classList.toggle('hidden',training);}
function renderChat(){const c=$('chat');c.innerHTML=state.transcript.map(m=>'<div class="message '+(m.role==='student'?'student':'patient')+'"><div class="bubble"><div class="role">'+(m.role==='student'?'學生':'模擬病人')+'</div><div>'+esc(m.content)+'</div></div></div>').join('');c.scrollTop=c.scrollHeight;$('turnCount').textContent=state.transcript.filter(m=>m.role==='student').length;}
function renderCoach(d=state.coach){if(state.mode!=='training')return;$('coachEmpty').classList.toggle('hidden',!!d);$('coachContent').classList.toggle('hidden',!d);if(!d){$('trainingProgress').textContent='0/?';return}$('trainingProgress').textContent=d.progress.covered+'/'+d.progress.total;$('coachQuality').textContent=d.lastQuestion?.level==='good'?'問句品質良好':'可再精進';$('coachQuality').className=d.lastQuestion?.level==='good'?'quality-good':'quality-needs';$('coachComment').textContent=d.lastQuestion?.comment||'';$('coachHint').textContent=d.nextHint;$('coachReflection').textContent=d.reflectionPrompt;}
async function post(url,payload){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(url);return r.json();}
async function ask(q){state.transcript.push({role:'student',content:q,at:new Date().toISOString()});renderChat();$('sendBtn').disabled=true;try{const d=await post('/api/chat',{caseId:state.caseId,message:q,revealedFactIds:state.revealedFactIds});state.revealedFactIds=d.revealedFactIds;state.transcript.push({role:'patient',content:d.reply,at:new Date().toISOString()});if(state.mode==='training')state.coach=await post('/api/coach',{caseId:state.caseId,transcript:state.transcript,revealedFactIds:state.revealedFactIds});save();renderChat();renderCoach();}catch{state.transcript.push({role:'patient',content:'（系統暫時無法取得回覆。）'});renderChat();}finally{$('sendBtn').disabled=false;}}
function renderEvaluation(d){$('resultCard').classList.remove('hidden');$('scoreCircle').textContent=String(d.percentage);$('resultMode').textContent=modeLabel(d.mode)+' · '+d.totalScore+'/'+d.maxScore+' 分';$('overallComment').textContent=d.overall.comment;$('strengthList').innerHTML=d.overall.strengths.map(x=>'<li>'+esc(x)+'</li>').join('');$('improvementList').innerHTML=d.overall.improvements.map(x=>'<li>'+esc(x)+'</li>').join('');$('recommendationList').innerHTML=d.overall.recommendations.map(x=>'<li>'+esc(x)+'</li>').join('');$('nextPracticeFocus').textContent=d.overall.nextPracticeFocus;$('rubricTable').innerHTML=d.items.map(i=>'<div class="rubric-item"><div class="rubric-main"><strong>'+esc(i.criterion)+'</strong><span>'+i.score+'/'+i.maxScore+'</span><span class="status status-'+i.status+'">'+(i.status==='covered'?'完整涵蓋':i.status==='partial'?'部分涵蓋':'未涵蓋')+'</span></div><div class="rubric-detail"><span>'+esc(i.reasoning)+'</span>'+(i.evidence?.[0]?'<span class="evidence-quote">證據：「'+esc(i.evidence[0].quote)+'」</span>':'')+'</div></div>').join('');}
async function finish(){try{const d=await post('/api/evaluate',{caseId:state.caseId,transcript:state.transcript,revealedFactIds:state.revealedFactIds,mode:state.mode});renderEvaluation(d);const rec={id:state.sessionId,studentName:state.studentName||'未填姓名',caseTitle:state.caseData.title,mode:state.mode,completedAt:new Date().toISOString(),transcript:state.transcript,evaluation:d};state.records=read(RKEY,[]);const ix=state.records.findIndex(x=>x.id===rec.id);if(ix>=0)state.records[ix]=rec;else state.records.unshift(rec);write(RKEY,state.records);renderRecords();}catch{alert('評量失敗');}}
function renderCases(){$('teacherCaseList').innerHTML=state.cases.map(c=>'<div class="manage-row"><div><strong>'+esc(c.title)+'</strong><small>'+esc(c.patient?.name||'')+' · '+esc(c.difficulty||'')+' · '+(c.learningGoals||[]).length+' 個學習目標</small></div><span class="readonly-pill">POC 病例</span></div>').join('');}
function renderRecords(){state.records=read(RKEY,[]);$('recordCount').textContent=state.records.length;$('trainingCount').textContent=state.records.filter(r=>r.mode==='training').length;$('examCount').textContent=state.records.filter(r=>r.mode==='exam').length;const scored=state.records.filter(r=>Number.isFinite(r.evaluation?.percentage));$('averageScore').textContent=scored.length?Math.round(scored.reduce((a,r)=>a+r.evaluation.percentage,0)/scored.length)+'%':'--';$('recordList').innerHTML=state.records.length?state.records.map(r=>'<button class="record-row" data-id="'+esc(r.id)+'"><span><strong>'+esc(r.studentName)+'</strong><small>'+esc(r.caseTitle)+'</small></span><span class="record-mode '+r.mode+'">'+(r.mode==='training'?'訓練':'考試')+'</span><span>'+new Date(r.completedAt).toLocaleString('zh-TW')+'</span><b>'+(r.evaluation?.percentage??'--')+'%</b></button>').join(''):'<p class="empty">尚無完成紀錄。</p>';$('recordList').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>showRecord(b.dataset.id));}
function showRecord(id){const r=state.records.find(x=>x.id===id);if(!r)return;$('recordDetail').classList.remove('hidden');$('recordDetailTitle').textContent=r.studentName+' · '+r.caseTitle;$('recordMeta').textContent=modeLabel(r.mode)+' · '+new Date(r.completedAt).toLocaleString('zh-TW')+' · '+r.evaluation.percentage+' 分';$('recordOverall').innerHTML='<strong>AI 總評</strong><p>'+esc(r.evaluation.overall?.comment||'')+'</p>';$('recordTranscript').innerHTML=r.transcript.map(m=>'<div class="audit-turn '+m.role+'"><strong>'+(m.role==='student'?'學生':'病人')+'</strong><span>'+esc(m.content)+'</span></div>').join('');$('recordRubric').innerHTML=r.evaluation.items.map(i=>'<div class="teacher-item"><strong>'+esc(i.criterion)+'</strong><span>'+i.score+'/'+i.maxScore+' · '+(i.status==='covered'?'完整':i.status==='partial'?'部分':'未涵蓋')+'</span></div>').join('');}
function switchMode(m){if(m===state.mode)return;if(!confirm('切換模式會重新開始本病例，確定嗎？')){$('modeSelect').value=state.mode;return}state.mode=m;start();}
function switchCase(id){const c=state.cases.find(x=>x.id===id);if(!c)return;state.caseId=id;state.caseData=c;start();}
async function init(){state.records=read(RKEY,[]);const r=await fetch('/api/cases');const d=await r.json();state.cases=d.cases;state.caseData=state.cases[0];$('caseSelect').innerHTML=state.cases.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.title)+'</option>').join('');renderCases();renderRecords();start();}
$('chatForm').onsubmit=e=>{e.preventDefault();const i=$('messageInput'),q=i.value.trim();if(!q)return;i.value='';ask(q);};
$('finishBtn').onclick=finish;$('resetBtn').onclick=start;$('caseSelect').onchange=e=>switchCase(e.target.value);$('modeSelect').onchange=e=>switchMode(e.target.value);$('studentName').oninput=e=>{state.studentName=e.target.value;save();};$('closeRecordBtn').onclick=()=>$('recordDetail').classList.add('hidden');
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');});
document.querySelectorAll('.teacher-subtab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.teacher-subtab,.teacher-view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view==='cases'?'teacherCases':'teacherRecords').classList.add('active');if(b.dataset.view==='records')renderRecords();});
$('newCaseBtn').onclick=()=>alert('病例 Builder 已在上一版 POC 驗證；正式資料庫版會保留該流程並加入病例版本控管。');
init();